### ISSUE TITLE
JSON ne peut pas serialiser une clef crypté par RSA

### ISSUE THREAD

**Issue by Julien00859** [Peer-to-Text/Cobra#1]
`client.send(json.dumps({"command":"RSA-Auth-Send","Auth-Pass":self.clients[profile.uuid]["profile"].public_key.encrypt(self.clients[profile.uuid]["socket"][client]["RSA-Pass"], self.random.read(16))[0].decode()}).encode("UTF-8"))`

Ce qui est important à comprendre:

`public_key.encrypt(["RSA-Pass"]).decode()}).encode("UTF-8"))`

Génère l'erreur suivante:

    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
        self.run()
      File "C:\Users\Julien\Programmation\Peer-to-Text\protocol\server.py", line 142, in run
        client.send(json.dumps({"command":"RSA-Auth-Send","Auth-Pass":self.clients[profile.uuid]["profile"].public_key.encrypt(self.clients[profile.uuid]["socket"][client]["RSA-Pass"], self.random.read(16))[0].decode()}).encode("UTF-8"))

    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 0: invalid start byte

Le problème vient du fait que JSON ne peut pas sérialiser des bytes. Hors RSA retournera toujours des strings de bytes (ces bytes n'ayant rien à voir avec le tableau ascii dans leur nature). Le problème c'est que je suis obligé de transformer ces bytes en string pour être compris par le JSON (qui sera encore par la suite re-convertis en byte pour être envoyé sur le socket) ce qui génère une erreur car decode() tente d'interpréter ces caractères ou un truc dans le genre

**Comment by Julien00859** [comment]
si on decode en utilisant "latin-1" aucune erreur est levé (le password crypté par RSA)
ensuite l'encoding du json en UTF-8 passe bien
mais le decoding ne suit plus `ValueError: Invalid \uXXXX escape: line 1 column 1020 (char 1019)`

**Comment by Julien00859** [comment]
Quand je retest en local ça marche crème... :'( (gen une key, encode latin-1, json, encode utf-8, envoie socket, reception socket, decode utf-8, decode latin-1, print key)

**Comment by Julien00859** [comment]
en utilisant l'encoding latin-1 (pour décoder le mot de passe crypé) ça passe crème. Mais la longueur est plus grande que 1024 bytes ce qui fait planter le serveur (qui n'écoute que 1024 bytes). Même en écoutant 2048 bytes, ça bug...

**Comment by Julien00859** [comment]
Le bug vient du fait que le ping est envoyé en même temps que RSA-Auth-Send.
J'ai corrigé temporairement en commenant le ping

**Comment by Julien00859** [comment]
Corrigé définitivement, les commandes json sont toutes espacées par une virgule
